### PR TITLE
Create LICENSE

### PR DESCRIPTION
**Pull request by andrewn6**

### CODE REVIEW

**Comment by andrewn6** [comment]
Do you think it's needed to use a license I am just using MIT since its one of the most used for a good reason.. lmk what you think about this @PineappleRind @TheCodingGuru.

**Comment by ShalomMande** [comment]
Alright, thank you.

**Comment by andrewn6** [comment]
So should i add the license?
or wait til @TheCodingGuru comes?

**Comment by ShalomMande** [comment]
It entirely depends on you

**Comment by andrewn6** [comment]
ok ill probably just merge it then

**Comment by andrewn6** [comment]
alright, it's merged :)

**Comment by ShalomMande** [comment]
Alright.

**Pull request merged**
