### PR TITLE
URGENT Fixed your gitignore

### PR DESCRIPTION
**Pull request by flopana**
You accidentally checked in your secrets.py please revoke your discord toke and create a new one

### CODE REVIEW

**Comment by andrewn6** [comment]
oh shoot thanks so much! next time to ignore a certain file do i do *filename.py? (fyi i regenerated the token right away again tysm)

**Comment by flopana** [comment]
> oh shoot thanks so much! next time to ignore a certain file do i do *filename.py?

no just type in the filename itself like I did in 886e7e982306d6fa156b5b190aac06ed857d7d40
the * is a wildcard so if you wanted to ignore everything ending in `.exe` you would write `*.exe`
there are many different types of wildcards I'll link you a gitignore cheat sheet 
[.gitignore cheat sheet](https://github.com/kenmueller/gitignore)

Good to know you regenerated it 👍  next time please be aware of ignoring files like this properly ^^

**Comment by andrewn6** [comment]
ah ok thanks alot :D

**Comment by flopana** [comment]
You're welcome mate ^^
Greetings from Germany 🇩🇪

**Pull request merged**
